/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flipzu_FzFormat */

#ifndef _Included_com_flipzu_FzFormat
#define _Included_com_flipzu_FzFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flipzu_FzFormat
 * Method:    getFormat
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flipzu_FzFormat_getFormat
  (JNIEnv *, jclass, jbyteArray, jint );

#ifdef __cplusplus
}
#endif
#endif
